export const States = [
  { state: "ANDAMAN & NICOBARr" },
  { state: "ANDHRA PRADESH" },
  { state: "ARUNACHAL PRADESH" },
  { state: "ASSAM" },
  { state: "BIHAR" },
  { state: "CHANDIGARH" },
  { state: "CHATTISGARH" },
  { state: "DADRA & NAGAR HAVELI" },
  { state: "DAMAN & DIU" },
  { state: "DELHI" },
  { state: "GOA" },
  { state: "GUJARAT" },
  { state: "HARYANA" },
  { state: "HIMACHAL PRADESH" },
  { state: "JAMMU & KASHMIR" },
  { state: "JHARKHAND" },
  { state: "KARNATAKA" },
  { state: "KERALA" },
  { state: "LAKSHADWEEP" },
  { state: "MADHYA PRADESH" },
  { state: "MAHARASHTRA" },
  { state: "MANIPUR" },
  { state: "MEGHALAYA" },
  { state: "MIZORAM" },
  { state: "NAGALAND" },
  { state: "ODISHA" },
  { state: "PONDICHERRY" },
  { state: "PUNJAB" },
  { state: "RAJASTHAN" },
  { state: "SIKKIM" },
  { state: "TAMIL NADU" },
  { state: "TELANGANA" },
  { state: "TRIPURA" },
  { state: "UTTAR PRADESH" },
  { state: "UTTARAKHAND" },
  { state: "WEST BENGAL" },
];

export const sortingArray = [
  {
    title: "title",
    label: "Title (A-Z)",
  },
  {
    title: "title-reverse",
    label: "Title (Z-A)",
  },
  {
    title: "price-high-to-low",
    label: "Price (High to Low)",
  },
  {
    title: "price-low-to-high",
    label: "Price (Low to High)",
  },
  {
    title: "recently-added",
    label: "Recently Added",
  },
];
